# Generated by Django 4.1.7 on 2023-03-10 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название проекта')),
                ('link_to_repo', models.URLField(blank=True, max_length=300, verbose_name='Ссылка на репозиторий')),
                ('group_of_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователи проекта')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ToDO_body', models.CharField(max_length=1024, verbose_name='Текст заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Признак активности')),
                ('Project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todo.project', verbose_name='Название проекта задачи')),
                ('created_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь создавший задачу')),
            ],
        ),
    ]
