# Generated by Django 4.1.7 on 2023-03-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='name_of_project',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='Project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='ToDO_body',
            new_name='todo_body',
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Признак активности'),
        ),
    ]
