# Generated by Django 4.1.7 on 2023-04-02 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0002_rename_name_project_name_of_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь создавший задачу'),
        ),
        migrations.RemoveField(
            model_name='todo',
            name='project',
        ),
        migrations.AddField(
            model_name='todo',
            name='project',
            field=models.ManyToManyField(to='todo.project', verbose_name='Название проекта задачи'),
        ),
    ]
